/**
 * Connects casdey's Instagram account to the publisher: reads
 * INSTAGRAM_ACCESS_TOKEN from web/.env.local (generated in the Meta app
 * "casdey publisher", API setup with Instagram login), checks it against
 * Instagram, and stores it encrypted in public.instagram_account, where the
 * daily cron reads and renews it.
 *
 *   npm run ig:token
 *
 * Run it again only if the token ever has to be regenerated by hand. It never
 * prints the token.
 */

import { encryptToken, required, supabase } from "./instagram-env.mjs";

const token = required("INSTAGRAM_ACCESS_TOKEN");
const me = await fetch(`https://graph.instagram.com/v25.0/me?fields=user_id,username,account_type&access_token=${encodeURIComponent(token)}`).then((r) => r.json());
if (me.error) throw new Error(`Instagram rejected the token: ${me.error.message}`);
if (me.account_type !== "BUSINESS" && me.account_type !== "MEDIA_CREATOR") {
  throw new Error(`@${me.username} is a ${me.account_type} account; publishing needs a professional one`);
}

const { url, headers } = supabase();
const now = new Date().toISOString();
const res = await fetch(`${url}/rest/v1/instagram_account?on_conflict=id`, {
  method: "POST",
  headers: { ...headers, "content-type": "application/json", Prefer: "resolution=merge-duplicates,return=minimal" },
  body: JSON.stringify({ id: 1, ig_user_id: me.user_id, username: me.username, access_token_encrypted: encryptToken(token), token_refreshed_at: now, updated_at: now }),
});
if (!res.ok) throw new Error(`saving the account failed (${res.status}): ${await res.text()}`);
console.log(`Connected @${me.username} (${me.account_type}, id ${me.user_id}). Token stored encrypted.`);
